# Travis CI Configuration
# https://docs.travis-ci.com
## Currenly not exist :)
language: debian

## Use container-based infrastructure for quicker build start-up
sudo: false
addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - equivs
    - realpath      # Merged to GNU Coreutils in Ubuntu 16.04
    - shellcheck

## We only support Ubuntu 14.04 and newer
dist: trusty

script:
#- git ls-files -z \*.bash | xargs --max-args=1 --verbose --null -- shellcheck
# The following command will be dropped in favor with the above one after Travis CI environment contains ShellCheck >=0.4.5, which fixes the bug that triggers SC2148 even when `shell` directive is used
- git ls-files -z \*.bash | xargs --max-args=1 --verbose --null -- shellcheck --shell=bash
- ./build.bash

deploy:
  provider: releases
  api_key:
    secure: XZ/t7BGF2DDM81xQk+Mx/M4pWp/9FwLcyRy9YUtEanoWlxo2iguyeQ1QVqOd8OzMS52fCGV6MOVEdA7AkSCyvEv7lv9X8PLhO7pL5iNcpzfkxLFZrcKYuLFMFqch9fSmmFtaBYA8AOCRXAes2aRl7b0z300cr2rJhE0RGYEUq+zNDOTgvqmsd0Y7s9Gsrx+2Kz2DKxARChc3lCwJ5XbV0xWB3qoEmeMkRq/axCCNLcRsXqZ1U3CcBSnkj/Jz8tRiRHdj/Tf8y2PJNRI3xHNVuWP9dC+t1309lMWAbvAFIv4PrdZm3plVe6BcZ3MJrCpMgNicHpfyH2yR7AA29aQjs0zoekHu4Cm2ET1w8FIsAEMEUPyqhHXwfNCDCyWZ08eskcaB6gXWFlCjE8mebIL1LA1SmFrK2mxWtbFrzdfcUzK7fvsUpR+oAKscwzUSyVpgdA9kB/v6+cwXWGW94KkU/B1UX6sQ/+SoHMfsGAHGuZJjCSL4Abf7pF3T+8QhLqfKXJIURv2yFLN5vnfoALQ2x2PjQ9/3W2t2LjRTHaykculFcbPMLRBEYHAQj8awJPfeUgmzy2fCR1KA1KQc56OIodYpG5ZYd+Mb9nK1vGg2yA8ihx2s6pU7EKn/7UEbfYKMszxoqtPB0FhHEm/mfEJnCPfkea3V7415nwtSoidxhBM=
  skip_cleanup: true
  file_glob: true
  file: "*.deb"
  on:
    tags: true
